version: "2"
services:
  tasker:
    build: .
    image: tasker
    ports:
     - 8080
    environment:
      GITHUB_CLIENT_ID: 77f0c1f303d2e8c07120
      GITHUB_CLIENT_SECRET: e78b87862c0fd46e50e351ce0307b4eadca9167c
      MONGO_URL: mongodb://tasker:tasker@ds049180.mlab.com:49180/gamersdemokrasy
      PORT: 8080
